### ISSUE TITLE
Kopf des Charakters wird falsch vor Objekt gerendert

### ISSUE THREAD

**Issue by TheREALSenate** [DarkErik/ItsAMatterOfSize#5]
![image](https://user-images.githubusercontent.com/83612037/117834680-a3916800-b277-11eb-9df9-2cca98d185da.png)
@DarkErik 

Entweder wird der Kopf falsch vor dem Objekt gerendert oder der Körper wird weggelassen. Bei dem Schornstein der Lokomotive funktioniert es richtig.

**Comment by DarkErik** [comment]
Jo gut, dass du's sagst, werde ich fixen
